name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9', '3.10']
        include:
        - os: macos-latest
          python-version: '3.10'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (Mac)
      if: matrix.os == 'macos-latest'
      run: |
        brew install swig
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest-cov pytest-flake8
        # Get and build latest python-ihm
        git clone --depth=5 https://github.com/ihmwg/python-ihm
        (cd python-ihm && python setup.py build && python setup.py install)
    - name: Test
      run: |
        pytest --cov=ma --cov-branch --cov-report=xml --cov-append --flake8 -v .
    - uses: codecov/codecov-action@v1
